name: .NET Core Build with Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $config --no-restore
        
      - name: Display debug info
        run: |
          echo ${{ github.event_name }}
          # echo 
